"""Concept dictionary for the attention overlay.

Each entry has:
  - id:       short slug used as the data-c attribute on tagged spans
  - label:    human-readable name (shown in tooltips / debug)
  - patterns: list of regex strings (compiled case-insensitively, word-bounded
              where stated). The matcher picks the longest non-overlapping
              spans, so "common good" wins over a separate "good" match.

Notes on curation:
  - Concepts must be lexically distinct enough to avoid catching common words
    in the wrong sense ("just", "free", "true" alone are too noisy).
  - We aim for ~50 concepts so the co-occurrence graph has enough density
    to feel meaningful without being a wall of highlights.
"""

CONCEPTS: list[dict] = [

    # --- Theology / God -----------------------------------------------------
    {"id": "god",          "label": "God",            "patterns": [r"\bGod\b", r"\bGod's\b"]},
    {"id": "christ",       "label": "Christ",         "patterns": [r"\bChrist\b", r"\bJesus\b", r"\bSon of God\b", r"\bIncarnate Word\b"]},
    {"id": "spirit",       "label": "Holy Spirit",    "patterns": [r"\bHoly Spirit\b"]},
    {"id": "trinity",      "label": "Trinity",        "patterns": [r"\bTriune\b", r"\bTrinitarian\b", r"\bTrinity\b"]},
    {"id": "incarnation",  "label": "Incarnation",    "patterns": [r"\bIncarnation\b", r"\bIncarnate\b", r"\bWord became flesh\b"]},
    {"id": "cross",        "label": "Cross",          "patterns": [r"\bCross\b", r"\bcrucified\b", r"\bcrucifixion\b", r"\bPaschal\b"]},
    {"id": "resurrection", "label": "resurrection",   "patterns": [r"\bresurrection\b", r"\brisen\b", r"\bEaster\b"]},
    {"id": "salvation",    "label": "salvation",      "patterns": [r"\bsalvation\b", r"\bredemption\b", r"\bredeemed\b", r"\bsaving\b"]},
    {"id": "sin",          "label": "sin",            "patterns": [r"\bsin\b", r"\bsins\b", r"\bsinful\b", r"\bsinner\b", r"\bsinners\b"]},
    {"id": "grace",        "label": "grace",          "patterns": [r"\bgrace\b", r"\bgraced\b"]},
    {"id": "mercy",        "label": "mercy",          "patterns": [r"\bmercy\b", r"\bmerciful\b"]},
    {"id": "faith",        "label": "faith",          "patterns": [r"\bfaith\b", r"\bfaithful\b", r"\bfaithfulness\b", r"\bbelievers?\b"]},
    {"id": "prayer",       "label": "prayer",         "patterns": [r"\bprayer\b", r"\bpraying\b", r"\bpray\b"]},
    {"id": "gospel",       "label": "Gospel",         "patterns": [r"\bGospel\b"]},
    {"id": "church",       "label": "Church",         "patterns": [r"\bChurch\b", r"\becclesial\b"]},
    {"id": "magisterium",  "label": "Magisterium",    "patterns": [r"\bMagisterium\b", r"\bmagisterial\b"]},
    {"id": "eucharist",    "label": "Eucharist",      "patterns": [r"\bEucharist\b", r"\bEucharistic\b", r"\bsacrament\w*"]},
    {"id": "kingdom",      "label": "Kingdom of God", "patterns": [r"\bKingdom of God\b", r"\bKingdom\b"]},
    {"id": "synodality",   "label": "synodality",     "patterns": [r"\bsynodal\w*"]},
    {"id": "mission",      "label": "mission",        "patterns": [r"\bmission\b", r"\bmissionary\b", r"\bevangeli\w+"]},
    {"id": "saint",        "label": "saint",          "patterns": [r"\bsaint\b", r"\bsaints\b", r"\bmartyr\w*"]},
    {"id": "vocation",     "label": "vocation",       "patterns": [r"\bvocation\b", r"\bvocational\b", r"\bcalled to\b"]},
    {"id": "mystery",      "label": "mystery",        "patterns": [r"\bmystery\b", r"\bmysteries\b", r"\bmysterious\b"]},
    {"id": "glory",        "label": "glory",          "patterns": [r"\bglory\b", r"\bglorious\b"]},
    {"id": "sacred",       "label": "sacred",         "patterns": [r"\bsacred\b", r"\bsanctity\b", r"\bsanctif\w+", r"\bholiness\b"]},
    {"id": "worship",      "label": "worship",        "patterns": [r"\bworship\b", r"\bliturgy\b", r"\bliturgical\b"]},
    {"id": "conversion",   "label": "conversion",     "patterns": [r"\bconversion\b", r"\bconvert\w+", r"\brepent\w+"]},
    {"id": "transcendence","label": "transcendence",  "patterns": [r"\btranscend\w+"]},
    {"id": "tradition",    "label": "tradition",      "patterns": [r"\btradition\b", r"\btraditions\b", r"\btraditional\b"]},
    {"id": "holy-see",     "label": "Holy See",       "patterns": [r"\bHoly See\b", r"\bapostolic\b", r"\bpontiff\w*", r"\bpontificate\b"]},
    {"id": "bible",        "label": "Scripture",      "patterns": [r"\bSacred Scripture\b", r"\bScriptures?\b", r"\bBible\b", r"\bbiblical\b", r"\bgenesis\b", r"\brevelation\b"]},
    {"id": "father-god",   "label": "Father",         "patterns": [r"\bthe Father\b", r"\bheavenly Father\b"]},

    # --- Anthropology -------------------------------------------------------
    {"id": "person",       "label": "person",         "patterns": [r"\bperson\b", r"\bpersons\b", r"\bpersonal\b", r"\bhuman person\b"]},
    {"id": "dignity",      "label": "dignity",        "patterns": [r"\bdignity\b", r"\bdignified\b", r"\bdignifying\b", r"\bDignitas\b"]},
    {"id": "image-of-god", "label": "image of God",   "patterns": [r"\bimage of God\b", r"\bimago Dei\b", r"\bimage and likeness\b"]},
    {"id": "conscience",   "label": "conscience",     "patterns": [r"\bconscience\b", r"\bconsciences\b"]},
    {"id": "freedom",      "label": "freedom",        "patterns": [r"\bfreedom\b", r"\bliberty\b", r"\bliberat\w+"]},
    {"id": "responsibility","label": "responsibility","patterns": [r"\bresponsibility\b", r"\bresponsibilities\b", r"\bresponsible\b", r"\baccountab\w+"]},
    {"id": "limit",        "label": "limit/finitude", "patterns": [r"\blimit\b", r"\blimits\b", r"\blimitation\b", r"\blimitations\b", r"\bfinitude\b", r"\bfinite\b", r"\bvulnerab\w+", r"\bweakness\b"]},
    {"id": "relationship", "label": "relationship",   "patterns": [r"\brelationship\b", r"\brelationships\b", r"\brelational\b"]},
    {"id": "communion",    "label": "communion",      "patterns": [r"\bcommunion\b"]},
    {"id": "fraternity",   "label": "fraternity",     "patterns": [r"\bfraternity\b", r"\bfraternal\b", r"\bbrothers and sisters\b"]},
    {"id": "heart",        "label": "heart",          "patterns": [r"\bheart\b", r"\bhearts\b"]},
    {"id": "mind",         "label": "mind/intelligence", "patterns": [r"\bmind\b", r"\bminds\b", r"\bmindful\b", r"\bintelligence\b", r"\bintellect\w*", r"\breason\b", r"\brational\b"]},
    {"id": "soul",         "label": "soul",           "patterns": [r"\bsoul\b", r"\bsouls\b"]},
    {"id": "body",         "label": "body",           "patterns": [r"\bbody\b", r"\bbodies\b", r"\bbodily\b", r"\bflesh\b"]},
    {"id": "wisdom",       "label": "wisdom",         "patterns": [r"\bwisdom\b", r"\bwise\b", r"\bwisely\b"]},
    {"id": "discernment",  "label": "discernment",    "patterns": [r"\bdiscernment\b", r"\bdiscern\b", r"\bdiscerning\b"]},
    {"id": "memory",       "label": "memory",         "patterns": [r"\bmemory\b", r"\bmemories\b", r"\bremember\w*", r"\bhistorical memory\b"]},
    {"id": "service",      "label": "service",        "patterns": [r"\bservice\b", r"\bserve\b", r"\bserves\b", r"\bserving\b"]},
    {"id": "humanity",     "label": "humanity",       "patterns": [r"\bhumanity\b", r"\bhuman family\b", r"\bhuman beings?\b", r"\bhumankind\b"]},
    {"id": "society",      "label": "society",        "patterns": [r"\bsociety\b", r"\bsocieties\b", r"\bsocietal\b"]},
    {"id": "nature",       "label": "nature",         "patterns": [r"\bhuman nature\b", r"\bnature itself\b", r"\bnatural law\b"]},
    {"id": "vision",       "label": "vision",         "patterns": [r"\bvision\b", r"\bvisions\b"]},
    {"id": "conviction",   "label": "conviction",     "patterns": [r"\bconviction\b", r"\bconvictions\b"]},
    {"id": "decision",     "label": "decision",       "patterns": [r"\bdecision\b", r"\bdecisions\b", r"\bdecision-making\b", r"\bchoice\b", r"\bchoices\b"]},
    {"id": "gift",         "label": "gift",           "patterns": [r"\bgift\b", r"\bgifts\b", r"\bgift of self\b"]},
    {"id": "experience",   "label": "experience",     "patterns": [r"\bexperience\b", r"\bexperiences\b", r"\bexperienced\b", r"\blived experience\b"]},
    {"id": "presence",     "label": "presence",       "patterns": [r"\bpresence\b", r"\bpresent\b"]},
    {"id": "fear",         "label": "fear",           "patterns": [r"\bfear\b", r"\bfears\b", r"\bafraid\b", r"\bfearful\b"]},
    {"id": "joy",          "label": "joy",            "patterns": [r"\bjoy\b", r"\bjoyful\b", r"\brejoic\w+"]},
    {"id": "suffering",    "label": "suffering",      "patterns": [r"\bsuffering\b", r"\bsuffer\b", r"\bsuffers\b", r"\bsuffered\b", r"\bpain\b", r"\bsorrow\b", r"\bsorrows\b"]},
    {"id": "wound",        "label": "wound",          "patterns": [r"\bwound\b", r"\bwounds\b", r"\bwounded\b"]},
    {"id": "anthropology", "label": "anthropology",   "patterns": [r"\banthropolog\w+", r"\banthropocentr\w+"]},
    {"id": "autonomy",     "label": "autonomy",       "patterns": [r"\bautonomy\b", r"\bautonomous\b"]},
    {"id": "humanism",     "label": "humanism",       "patterns": [r"\bhumanism\b", r"\bhumanist\b", r"\bChristian humanism\b"]},

    # --- Social principles --------------------------------------------------
    {"id": "common-good",  "label": "common good",    "patterns": [r"\bcommon good\b"]},
    {"id": "subsidiarity", "label": "subsidiarity",   "patterns": [r"\bsubsidiarity\b"]},
    {"id": "solidarity",   "label": "solidarity",     "patterns": [r"\bsolidarity\b"]},
    {"id": "justice",      "label": "justice",        "patterns": [r"\bjustice\b", r"\binjustice\b", r"\binjustices\b", r"\bsocial justice\b"]},
    {"id": "rights",       "label": "rights",         "patterns": [r"\bhuman rights\b", r"\brights\b"]},
    {"id": "universal-destination", "label": "universal destination of goods", "patterns": [r"\buniversal destination of goods\b", r"\buniversal destination\b"]},
    {"id": "integral-development",  "label": "integral human development", "patterns": [r"\bintegral human development\b", r"\bintegral development\b", r"\bintegral ecology\b"]},
    {"id": "preferential-option",   "label": "option for the poor", "patterns": [r"\bpreferential option for the poor\b", r"\boption for the poor\b"]},
    {"id": "social-doctrine","label": "Social Doctrine","patterns": [r"\bSocial Doctrine\b", r"\bsocial teaching\b"]},
    {"id": "compendium",   "label": "Compendium",     "patterns": [r"\bCompendium of the Social Doctrine\b", r"\bCompendium\b"]},
    {"id": "ethics",       "label": "ethics",         "patterns": [r"\bethics\b", r"\bethical\b"]},
    {"id": "moral",        "label": "morality",       "patterns": [r"\bmoral\b", r"\bmorally\b", r"\bmorality\b"]},
    {"id": "principle",    "label": "principle",      "patterns": [r"\bprinciple\b", r"\bprinciples\b"]},
    {"id": "virtue",       "label": "virtue",         "patterns": [r"\bvirtue\b", r"\bvirtues\b", r"\bvirtuous\b", r"\bprudence\b", r"\bfortitude\b", r"\btemperance\b"]},
    {"id": "evil",         "label": "evil",           "patterns": [r"\bevil\b", r"\bevils\b"]},
    {"id": "good",         "label": "good",           "patterns": [r"\bgoodness\b", r"\bthe good\b"]},
    {"id": "inequality",   "label": "inequality",     "patterns": [r"\binequalit\w+", r"\bdisparit\w+", r"\bgap between\b"]},
    {"id": "diversity",    "label": "diversity",      "patterns": [r"\bdiversity\b", r"\bdiverse\b", r"\bpluralis\w*"]},
    {"id": "inclusion",    "label": "inclusion",      "patterns": [r"\binclusion\b", r"\binclusive\b"]},
    {"id": "women",        "label": "women",          "patterns": [r"\bwomen\b"]},
    {"id": "structure",    "label": "structures",     "patterns": [r"\bstructures?\b", r"\bstructural\b"]},
    {"id": "institutions", "label": "institutions",   "patterns": [r"\binstitution\b", r"\binstitutions\b", r"\binstitutional\b"]},

    # --- Vulnerability ------------------------------------------------------
    {"id": "poor",         "label": "poor",           "patterns": [r"\bpoor\b", r"\bpoverty\b", r"\bpoorest\b"]},
    {"id": "migrant",      "label": "migrant",        "patterns": [r"\bmigrant\b", r"\bmigrants\b", r"\bmigration\b", r"\brefugee\b", r"\brefugees\b"]},
    {"id": "child",        "label": "child",          "patterns": [r"\bchild\b", r"\bchildren\b", r"\badolescent\b", r"\badolescents\b", r"\byoung people\b"]},
    {"id": "elderly",      "label": "elderly",        "patterns": [r"\belderly\b", r"\bold age\b", r"\baged\b"]},
    {"id": "sick",         "label": "sick",           "patterns": [r"\bsick\b", r"\billness\b", r"\bdisease\b", r"\bhealing\b"]},
    {"id": "victim",       "label": "victim",         "patterns": [r"\bvictim\b", r"\bvictims\b"]},
    {"id": "slavery",      "label": "slavery",        "patterns": [r"\bslavery\b", r"\bslave\b", r"\bslaves\b", r"\btrafficking\b"]},
    {"id": "exclusion",    "label": "exclusion",      "patterns": [r"\bexclusion\b", r"\bexcluded\b", r"\bmarginal\w+", r"\bdiscriminat\w+"]},

    # --- People -------------------------------------------------------------
    {"id": "augustine",    "label": "Augustine",      "patterns": [r"\bAugustine\b"]},
    {"id": "aquinas",      "label": "Aquinas",        "patterns": [r"\bAquinas\b"]},
    {"id": "francis",      "label": "Pope Francis",   "patterns": [r"\bPope Francis\b", r"\bFrancis\b"]},
    {"id": "leo-xiii",     "label": "Leo XIII",       "patterns": [r"\bLeo XIII\b"]},
    {"id": "john-paul-ii", "label": "John Paul II",   "patterns": [r"\bJohn Paul II\b"]},
    {"id": "benedict-xvi", "label": "Benedict XVI",   "patterns": [r"\bBenedict XVI\b"]},
    {"id": "paul-vi",      "label": "Paul VI",        "patterns": [r"\bPaul VI\b"]},
    {"id": "pius-xi",      "label": "Pius XI",        "patterns": [r"\bPius XI\b"]},
    {"id": "pius-xii",     "label": "Pius XII",       "patterns": [r"\bPius XII\b"]},
    {"id": "john-xxiii",   "label": "John XXIII",     "patterns": [r"\bJohn XXIII\b"]},
    {"id": "apostle-paul", "label": "Saint Paul",     "patterns": [r"\bSaint Paul\b(?! VI)", r"\bApostle Paul\b", r"\bSt\. Paul\b(?! VI)", r"\bthe Apostle\b"]},
    {"id": "guardini",     "label": "Guardini",       "patterns": [r"\bRomano Guardini\b", r"\bGuardini\b"]},
    {"id": "frankl",       "label": "Viktor Frankl",  "patterns": [r"\bViktor Frankl\b", r"\bFrankl\b"]},
    {"id": "arendt",       "label": "Hannah Arendt",  "patterns": [r"\bHannah Arendt\b", r"\bArendt\b"]},
    {"id": "plato",        "label": "Plato",          "patterns": [r"\bPlato\b"]},
    {"id": "nehemiah",     "label": "Nehemiah",       "patterns": [r"\bNehemiah\b"]},
    {"id": "mary",         "label": "Mary",           "patterns": [r"\bBlessed Virgin Mary\b", r"\bBlessed Virgin\b", r"\bMary\b", r"\bMagnificat\b"]},

    # --- Biblical / theological images --------------------------------------
    {"id": "babel",        "label": "Babel",          "patterns": [r"\bBabel\b", r"\bTower of Babel\b"]},
    {"id": "jerusalem",    "label": "Jerusalem",      "patterns": [r"\bJerusalem\b"]},
    {"id": "two-cities",   "label": "two cities",     "patterns": [r"\btwo cities\b", r"\bcity of God\b", r"\bearthly city\b", r"\bheavenly city\b"]},
    {"id": "civilization-of-love", "label": "civilization of love", "patterns": [r"\bcivilization of love\b"]},

    # --- Documents ----------------------------------------------------------
    {"id": "rerum-novarum","label": "Rerum Novarum",  "patterns": [r"\bRerum Novarum\b"]},
    {"id": "gaudium-et-spes","label": "Gaudium et Spes","patterns": [r"\bGaudium et Spes\b"]},
    {"id": "laudato-si",   "label": "Laudato Si'",    "patterns": [r"\bLaudato Si\W"]},
    {"id": "fratelli-tutti","label": "Fratelli Tutti","patterns": [r"\bFratelli Tutti\b"]},
    {"id": "vatican-ii",   "label": "Vatican II",     "patterns": [r"\bSecond Vatican Council\b", r"\bVatican II\b"]},
    {"id": "quadragesimo", "label": "Quadragesimo Anno", "patterns": [r"\bQuadragesim[ao] Anno\b"]},
    {"id": "pacem-in-terris","label": "Pacem in Terris","patterns": [r"\bPacem in Terris\b"]},
    {"id": "mater-et-magistra","label": "Mater et Magistra","patterns": [r"\bMater et Magistra\b"]},
    {"id": "populorum-progressio","label": "Populorum Progressio","patterns": [r"\bPopulorum Progressio\b"]},
    {"id": "octogesima",   "label": "Octogesima Adveniens", "patterns": [r"\bOctogesima Adveniens\b"]},
    {"id": "laborem",      "label": "Laborem Exercens","patterns": [r"\bLaborem Exercens\b"]},
    {"id": "sollicitudo",  "label": "Sollicitudo Rei Socialis","patterns": [r"\bSollicitudo Rei Socialis\b"]},
    {"id": "centesimus",   "label": "Centesimus Annus","patterns": [r"\bCentesimus Annus\b"]},
    {"id": "caritas-in-veritate","label": "Caritas in Veritate","patterns": [r"\bCaritas in Veritate\b"]},
    {"id": "evangelii-gaudium","label": "Evangelii Gaudium","patterns": [r"\bEvangelii Gaudium\b"]},
    {"id": "dilexit-nos",  "label": "Dilexit Nos",    "patterns": [r"\bDilexit Nos\b"]},
    {"id": "dignitatis-humanae","label": "Dignitatis Humanae","patterns": [r"\bDignitatis Humanae\b"]},
    {"id": "dignitas-infinita","label": "Dignitas Infinita","patterns": [r"\bDignitas Infinita\b"]},

    # --- Technology ---------------------------------------------------------
    {"id": "technology",   "label": "technology",     "patterns": [r"\btechnology\b", r"\btechnologies\b", r"\btechnological\b"]},
    {"id": "ai",           "label": "artificial intelligence", "patterns": [r"\bartificial intelligence\b", r"\bAI\b"]},
    {"id": "data",         "label": "data",           "patterns": [r"\bdata\b", r"\balgorithm\b", r"\balgorithms\b", r"\balgorithmic\b"]},
    {"id": "transhumanism","label": "transhumanism",  "patterns": [r"\btranshumanis\w*"]},
    {"id": "posthumanism", "label": "posthumanism",   "patterns": [r"\bposthumanis\w*"]},
    {"id": "technocratic", "label": "technocratic",   "patterns": [r"\btechnocratic\b", r"\btechnocracy\b"]},
    {"id": "digital",      "label": "digital",        "patterns": [r"\bdigital\b", r"\bdigitalization\b"]},
    {"id": "innovation",   "label": "innovation",     "patterns": [r"\binnovation\b", r"\binnovations\b", r"\binnovative\b"]},
    {"id": "surveillance", "label": "surveillance",   "patterns": [r"\bsurveillance\b", r"\bmonitor\w*", r"\bprofil\w+"]},
    {"id": "platform",     "label": "platform",       "patterns": [r"\bplatform\b", r"\bplatforms\b"]},
    {"id": "misinformation","label": "misinformation","patterns": [r"\bmisinformation\b", r"\bdisinformation\b", r"\bfake news\b", r"\bmanipulat\w+"]},
    {"id": "communication","label": "communication",  "patterns": [r"\bcommunication\b", r"\bcommunicate\b", r"\bcommunicating\b"]},
    {"id": "robotics",     "label": "robotics",       "patterns": [r"\brobot\w*"]},
    {"id": "biotechnology","label": "biotechnology",  "patterns": [r"\bbiotechnology\b", r"\bbiomedicine\b", r"\bgenetic\b", r"\bDNA\b"]},
    {"id": "automation",   "label": "automation",     "patterns": [r"\bautomation\b", r"\bautomated\b", r"\bautomatic\b"]},
    {"id": "machine",      "label": "machine",        "patterns": [r"\bmachine\b", r"\bmachines\b"]},
    {"id": "internet",     "label": "internet",       "patterns": [r"\bcyberspace\b", r"\bcyber\w*", r"\binternet\b", r"\bonline\b"]},
    {"id": "infrastructure","label": "infrastructure","patterns": [r"\binfrastructure\b", r"\binfrastructures\b"]},
    {"id": "research",     "label": "research",       "patterns": [r"\bresearch\b", r"\bscientific research\b"]},
    {"id": "science",      "label": "science",        "patterns": [r"\bscience\b", r"\bsciences\b", r"\bscientif\w+"]},

    # --- Work / economy ----------------------------------------------------
    {"id": "work",         "label": "work",           "patterns": [r"\bwork\b", r"\bworking\b", r"\bworkers\b", r"\blabor\b", r"\blabour\b", r"\blaboring\b"]},
    {"id": "economy",      "label": "economy",        "patterns": [r"\beconomy\b", r"\beconomic\b", r"\beconomies\b"]},
    {"id": "market",       "label": "market",         "patterns": [r"\bmarket\b", r"\bmarkets\b"]},
    {"id": "family",       "label": "family",         "patterns": [r"\bfamily\b", r"\bfamilies\b", r"\bfamilial\b"]},
    {"id": "profit",       "label": "profit",         "patterns": [r"\bprofit\b", r"\bprofits\b", r"\bprofitable\b", r"\bprofitability\b"]},
    {"id": "capital",      "label": "capital",        "patterns": [r"\bcapital\b", r"\bcapitalism\b", r"\bcapitalist\b"]},
    {"id": "wage",         "label": "wage",           "patterns": [r"\bwage\b", r"\bwages\b", r"\bsalary\b", r"\bremuneration\b"]},
    {"id": "finance",      "label": "finance",        "patterns": [r"\bfinance\b", r"\bfinancial\b"]},
    {"id": "industry",     "label": "industry",       "patterns": [r"\bindustry\b", r"\bindustrial\b", r"\bindustries\b"]},
    {"id": "exploitation", "label": "exploitation",   "patterns": [r"\bexploitation\b", r"\bexploit\b", r"\bexploited\b", r"\bexploiting\b"]},
    {"id": "consumerism",  "label": "consumerism",    "patterns": [r"\bconsumer\w*", r"\bconsumpt\w+"]},
    {"id": "unemployment", "label": "unemployment",   "patterns": [r"\bunemployment\b", r"\bunemployed\b", r"\bjob insecurity\b"]},
    {"id": "wealth",       "label": "wealth",         "patterns": [r"\bwealth\b", r"\bwealthy\b", r"\briches\b", r"\brich\b"]},

    # --- Politics / world --------------------------------------------------
    {"id": "state",        "label": "State",          "patterns": [r"\bState\b", r"\bStates\b", r"\bgovernment\b", r"\bgovernments\b"]},
    {"id": "democracy",    "label": "democracy",      "patterns": [r"\bdemocracy\b", r"\bdemocratic\b"]},
    {"id": "war",          "label": "war",            "patterns": [r"\bwar\b", r"\bwars\b", r"\bwarfare\b"]},
    {"id": "peace",        "label": "peace",          "patterns": [r"\bpeace\b", r"\bpeaceful\b", r"\bpeacemak\w+"]},
    {"id": "power",        "label": "power",          "patterns": [r"\bpower\b", r"\bpowers\b", r"\bpowerful\b"]},
    {"id": "weapon",       "label": "weapon",         "patterns": [r"\bweapon\b", r"\bweapons\b", r"\barms\b", r"\barmed\b", r"\bnuclear\b", r"\bmilitary\b"]},
    {"id": "nation",       "label": "nation",         "patterns": [r"\bnation\b", r"\bnations\b", r"\bpeoples\b", r"\binternational\b"]},
    {"id": "diplomacy",    "label": "diplomacy",      "patterns": [r"\bdiplomacy\b", r"\bdiplomatic\b", r"\bnegotiat\w+", r"\bmultilateral\w*"]},
    {"id": "globalization","label": "globalization",  "patterns": [r"\bglobalization\b", r"\bglobalized\b", r"\bglobal\b"]},
    {"id": "regulation",   "label": "regulation",     "patterns": [r"\bregulation\b", r"\bregulations\b", r"\bregulate\w*", r"\bregulator\w*"]},
    {"id": "governance",   "label": "governance",     "patterns": [r"\bgovernance\b"]},
    {"id": "violence",     "label": "violence",       "patterns": [r"\bviolence\b", r"\bviolent\b"]},
    {"id": "conflict",     "label": "conflict",       "patterns": [r"\bconflict\b", r"\bconflicts\b"]},
    {"id": "totalitarianism","label": "totalitarianism","patterns": [r"\btotalitarianism\b", r"\btotalitarian\b", r"\bfascism\b", r"\bfundamentalis\w+"]},
    {"id": "ideology",     "label": "ideology",       "patterns": [r"\bideology\b", r"\bideologies\b", r"\bideological\b"]},
    {"id": "realism",      "label": "realism",        "patterns": [r"\brealism\b", r"\brealist\w*", r"\bRealpolitik\b"]},
    {"id": "nihilism",     "label": "nihilism",       "patterns": [r"\bnihilism\b", r"\bnihilistic\b"]},
    {"id": "modernity",    "label": "modernity",      "patterns": [r"\bmodernity\b", r"\bmodern world\b"]},
    {"id": "individualism","label": "individualism",  "patterns": [r"\bindividualism\b", r"\bindividualistic\b", r"\bself-sufficien\w+"]},
    {"id": "citizen",      "label": "citizen",        "patterns": [r"\bcitizen\b", r"\bcitizens\b", r"\bcitizenship\b", r"\bcivic\b", r"\bcivil society\b"]},
    {"id": "participation","label": "participation",  "patterns": [r"\bparticipation\b", r"\bparticipate\b", r"\bparticipating\b"]},
    {"id": "protection",   "label": "protection",     "patterns": [r"\bprotection\b", r"\bsafeguard\w+"]},
    {"id": "transformation","label": "transformation","patterns": [r"\btransformation\b", r"\btransform\b", r"\btransforms\b", r"\btransformed\b", r"\btransformative\b", r"\btransitioning\b", r"\btransition\b"]},
    {"id": "crisis",       "label": "crisis",         "patterns": [r"\bcrisis\b", r"\bcrises\b"]},
    {"id": "change",       "label": "change",         "patterns": [r"\bchange\b", r"\bchanges\b", r"\bchanging\b", r"\bchanged\b"]},
    {"id": "progress",     "label": "progress",       "patterns": [r"\bprogress\b", r"\bprogressive\b", r"\bprogressed\b"]},
    {"id": "polarization", "label": "polarization",   "patterns": [r"\bpolariz\w+"]},
    {"id": "trust",        "label": "trust",          "patterns": [r"\btrust\b", r"\btrusts\b", r"\btrusted\b", r"\btrustworth\w+", r"\bmistrust\b"]},
    {"id": "civilization", "label": "civilization",   "patterns": [r"\bcivilization\b", r"\bcivilizations\b"]},

    # --- Knowledge / culture ----------------------------------------------
    {"id": "truth",        "label": "truth",          "patterns": [r"\btruth\b", r"\btruths\b", r"\btruthful\b"]},
    {"id": "education",    "label": "education",      "patterns": [r"\beducation\b", r"\beducational\b", r"\beducators?\b", r"\bteach\w+"]},
    {"id": "school",       "label": "school",         "patterns": [r"\bschool\b", r"\bschools\b", r"\buniversit\w+"]},
    {"id": "dialogue",     "label": "dialogue",       "patterns": [r"\bdialogue\b", r"\blisten\w*"]},
    {"id": "culture",      "label": "culture",        "patterns": [r"\bculture\b", r"\bcultures\b", r"\bcultural\b"]},
    {"id": "love",         "label": "love",           "patterns": [r"\blove\b", r"\bloving\b", r"\bloves\b", r"\bbeloved\b", r"\bcharity\b"]},
    {"id": "hope",         "label": "hope",           "patterns": [r"\bhope\b", r"\bhopeful\b"]},
    {"id": "creation",     "label": "creation",       "patterns": [r"\bcreation\b", r"\bcreatures?\b", r"\bcreator\b", r"\bcommon home\b"]},
    {"id": "history",      "label": "history",        "patterns": [r"\bhistory\b", r"\bhistorical\b", r"\bhistorically\b"]},
    {"id": "future",       "label": "future generations","patterns": [r"\bfuture generations?\b", r"\bgenerations to come\b", r"\bsucceeding generations\b"]},
    {"id": "signs-of-times","label": "signs of the times","patterns": [r"\bsigns of the times\b", r"\bres novae\b", r"\bnew things\b"]},
    {"id": "encounter",    "label": "encounter",      "patterns": [r"\bculture of encounter\b", r"\bencounter\b"]},
]
